### ISSUE TITLE
Missing return in constructor leading to memory overwrite possible SIGSEGV

### ISSUE THREAD

**Issue by sdrsdr** [staropram/cantcoap#12]
In CoapPDU::CoapPDU(uint8_t *buffer, int bufferLength, int pduLength)  construcotr

https://github.com/staropram/cantcoap/blob/master/cantcoap.cpp#L138 

there is a minimal buffer size check that leads to  debug message but there is no return so the execution continues and the memory after the short buffer is zeroed. Probably not a real world issue but should be fixed!

**Comment by staropram** [comment]
The memory is only zeroed for the special case of the pdu having a length of 0, if the pdulength is 1,2, or 3 then nothing happens.

**Comment by sdrsdr** [comment]
It is possible to recv a zero data size udp packet if such packet is used in pdu construction your code is going to do some bad memory writes.

**Comment by staropram** [comment]
It is upto the programmer to ensure that the buffer contains enough space for a minimum length PDU, i.e  4 bytes. The only issue here is if the programmer does not provide a buffer with at least 4 bytes.

It is upto the programmer to accurately specify the bufferLength variable so that it reflects the actual size of the buffer. If you really think this is an issue, I can check the bufferLength variable, and return if that is not >=4. Would you be happy with this?

**Comment by sdrsdr** [comment]
I'm happy with this as is .. I'm already checking my buffers as you suggest so no problem with me. :) I was just looking at your code and thought "I would have put a return here" so I submitted a issue. No sweat have a beer :beer:  :)

**Comment by staropram** [comment]
OK cool. Thanks for the input. If you notice anything else strange please let me know :)
