### ISSUE TITLE
Is OSCORE planned to be integrated in cantcoap?

### ISSUE THREAD

**Issue by biboc** [staropram/cantcoap#28]
Hi,

Is OSCORE planned to be integrated in cantcoap?
https://ioterop.com/oscore-for-iot-security-building-sustainable-lpwan-solutions/

Thanks,

**Comment by staropram** [comment]
it looks pretty cool, would be good to have it. The issue is, I'm not really using CoAP for anything at the moment so there isn't a direct driver for me to add it. If someone wants to look at it, that would be cool. I should have a bit more free time this year, so I'll keep it in mind as a task to look at.
