### ISSUE TITLE
Little Endian problem

### ISSUE THREAD

**Issue by romixlab** [staropram/cantcoap#5]
Hello! I tried to use your library on a x86 machine, and noticed, that integers are encoded incorrectly (for example in CoapPDU::setMessageID). Endiannes is always a problem, so maybe this will help: https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h

**Comment by staropram** [comment]
thanks, do you have time to submit a patch? 

ash 

On 2015-05-25 06:36, Roman wrote: 

> Hello! I tried to use your library on a x86 machine, and noticed, that integers are encoded incorrectly (for example in CoapPDU::setMessageID). Endiannes is always a problem, so maybe this will help: https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h [1] 
> 
> --
> Reply to this email directly or view it on GitHub [2].

 

Links:
------
[1]
https://github.com/msgpack/msgpack-c/blob/master/include/msgpack/sysdep.h
[2] https://github.com/staropram/cantcoap/issues/5

**Comment by romixlab** [comment]
Have some progress here: https://github.com/romixlab/cantcoap
seems to be working, test is ok

**Comment by staropram** [comment]
cool! thansk dude, I need to find some time to check it out and merge it

**Comment by staropram** [comment]
OK I had a look at this, there is an easier fix which is this:

```c
int CoapPDU::setMessageID(uint16_t messageID) {
	// message ID is stored in network byte order
	uint16_t networkOrder = htons(messageID);
	memcpy(&_pdu[2],&networkOrder,2);
	return 0;
}

/// Returns the 16 bit message ID of the PDU.
uint16_t CoapPDU::getMessageID() {
	// message ID is stored in network byteorder
	uint16_t networkOrder = 0x0000;
	memcpy((uint8_t*)&networkOrder,&_pdu[2],2);
	return ntohs(networkOrder);
}
```

Essentially the issue was in that the bitwise operations are done in the register, so originally after networkOrder was obtained in setMessageID, this was then stored in memory in little endian, the bitwise operations "convert" this back to "big endian" for manipulation, which is then wrong.

But I'm going to use your patch since it includes some stuff for legacy windows support which some people might find useful.

Thanks again for the input, sorry it took me so long to take a look at this.

**Comment by staropram** [comment]
Closing as the fix is now merged.

**Comment by romixlab** [comment]
Glad I could help!
